spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3307/book_manager?characterEncoding=utf8
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: INFO